Repository CS2103JAN2018-T09-B2/main, pull requests merged in 2018-04, with the labels that each got.

#195 V1.5 bug fixes 1
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/CompleteGoalCommand.java
Labels: bug.fix

#198 UG changes
  docs/UserGuide.adoc
Labels: type.documentation

#201 V1.5 add sort goals
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/SortGoalCommand.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/logic/parser/AddGoalCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortGoalCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/goal/Completion.java
  src/main/java/seedu/address/model/goal/EndDateTime.java
  src/main/java/seedu/address/model/goal/Importance.java
  src/main/java/seedu/address/model/goal/StartDateTime.java
  src/main/java/seedu/address/model/goal/UniqueGoalList.java
  src/main/java/seedu/address/model/goal/exceptions/EmptyGoalListException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGoalCommandTest.java
  src/test/java/seedu/address/logic/commands/GoalCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortGoalCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortGoalCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/goal/ImportanceTest.java
  src/test/java/seedu/address/model/goal/StartDateTimeTest.java
Labels: type.enhancement, type.task

#204 Tag colours change
  src/main/java/seedu/address/ui/GoalCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.task

#212 Project portfolio page
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/deborahlow97.adoc
Labels: type.documentation

#219 Update collate
  collated/functional/deborahlow97.md
  collated/functional/fuadsahmawi.md
  collated/main/A0158738X.md
  collated/main/deborahlow97.md
  collated/main/fuadsahmawi.md
  collated/main/sham-sheer.md
Labels: type.task

#225 CollegeZone finalised UI
  README.adoc
  docs/UserGuide.adoc
  docs/images/UI.JPG
  docs/images/Ui.png
  src/main/java/seedu/address/ui/GoalCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/GoalListCard.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: type.task

#226 V1.5 user guide
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/OngoingGoalCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/SampleGoalDataUtil.java
Labels: type.documentation, type.fixBugs

#229 Update use cases and NFR
  docs/DeveloperGuide.adoc
Labels: type.documentation

#241 Edit user guide
  docs/UserGuide.adoc
  docs/images/addReminder.PNG
  docs/images/delReminder.PNG
  src/main/java/seedu/address/logic/commands/AddReminderCommand.java
Labels: type.task

#242 V1.5 documentation
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/images/sham-sheer.jpg
Labels: type.documentation

#245 Edit user guide
  docs/UserGuide.adoc
Labels: type.documentation

#246 V1.5 documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ModelComponentCollegeZone.PNG
  docs/images/StorageComponentCollegeZone.PNG
  docs/images/UserGuideLabelledUI.PNG
Labels: type.documentation

#247 V1.5 documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CollegeZoneBubblegumTheme.JPG
  docs/images/CollegeZoneDarkTheme.JPG
  docs/images/CollegeZoneLightTheme.JPG
Labels: type.documentation

#248 Edit developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/addReminderSeqDiagram.PNG
  docs/images/delReminderSeqDiagram.PNG
  docs/team/fuadsahmawi.adoc
  src/main/java/seedu/address/model/reminder/exceptions/DuplicateReminderException.java
Labels: type.documentation

#252 V1.5 documentation
  docs/DeveloperGuide.adoc
  docs/images/AddGoalSeqDiagram.PNG
  docs/images/CollegeZoneGoalModelClassDiagram.JPG
  docs/images/CompleteGoalSeqDiagram.PNG
  docs/images/DeleteGoalSeqDiagram.PNG
  docs/images/EditGoalSeqDiagram.PNG
  docs/images/SortGoalSeqDiagram.PNG
Labels: type.documentation

#256 V1.5 final dev guide edit
  docs/DeveloperGuide.adoc
  docs/team/gohzuwei.adoc
Labels: type.documentation

#255 V1.5 coderefactoring and more documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddGoal.PNG
  docs/images/CompleteGoal.PNG
  docs/images/DeleteGoal.PNG
  docs/images/EditGoal.PNG
  docs/images/OngoingGoal.PNG
  docs/images/SortGoal.PNG
  docs/images/appveyor/DownloadJar.JPG
  docs/team/deborahlow97.adoc
  src/main/java/seedu/address/logic/commands/CompleteGoalCommand.java
  src/main/java/seedu/address/logic/parser/CompleteGoalCommandParser.java
  src/main/java/seedu/address/model/goal/UniqueGoalList.java
  src/test/java/seedu/address/logic/commands/AddGoalCommandTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: type.documentation, type.fixBugs

#271 Fixed birthday bug
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: bug.fix, type.task

#272 Final update
  docs/DeveloperGuide.adoc
  docs/team/deborahlow97.adoc
  src/test/java/seedu/address/logic/commands/SortGoalCommandTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
Labels: type.documentation, type.task

#273 Fix typos
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.task

#276 Update Ui.png
  README.adoc
  collated/test/fuadsahamwi.md
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: type.documentation, type.task

#277 Shorten my portfolio
  docs/team/deborahlow97.adoc
Labels: type.documentation
